services:
  app:
    image: crpi-akjhmoniw59yirfb.cn-hangzhou.personal.cr.aliyuncs.com/seeridia/maynooth-moodle-ics:${IMAGE_TAG:?IMAGE_TAG must be set}
    container_name: maynooth-moodle-ics
    restart: always
    ports:
      - "4700:3000"
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
